###############################################################################
##########                                                           ##########
##########                DO NOT EDIT THIS FILE !                    ##########
##########                                                           ##########
###############################################################################

import os
import sys
import json
import copy
import requests

import ai

url_prefix = 'https://www.xxxxx.com/checkers/'

###############################################################################

class InvalidMoveException(Exception):
    pass

class GameOver(Exception):
    def __init__(self, winner):
        super(GameOver, self).__init__()
        self.winner = winner

###############################################################################
